---
apiVersion: v1
kind: Namespace
metadata:
  name: filewcount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filewcount
  name: filewcount
  namespace: filewcount
spec:
  replicas: 3
  selector:
    matchLabels:
      app: filewcount
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: filewcount
    spec:
      containers:
      - image: bldrtech/filewcount
        name: filewcount
        resources:
          limits:
            cpu: 800m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: filewcount
  name: filewcount
  namespace: filewcount
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: filewcount
  type: ClusterIP
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
  name: ingress-nginx
  namespace: filewcount
spec:
  chart:
    spec:
      chart: ingress-nginx
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: '*'
  interval: 5m
  values: {}

# HorizontalPodAutoScaler
# Service
# Ingress
# Ingress Controller
# PodMonitor?