---
apiVersion: v1
kind: Namespace
metadata:
  name: filewcount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filewcount
  name: filewcount
  namespace: filewcount
spec:
  replicas: 3
  selector:
    matchLabels:
      app: filewcount
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: filewcount
    spec:
      containers:
      - image: bldrtech/filewcount:1.0
        name: filewcount
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 8Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: filewcount
  namespace: filewcount
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: filewcount
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: filewcount
  name: filewcount
  namespace: filewcount
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: filewcount
  type: ClusterIP
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: filewcount
#   namespace: filewcount
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: filewcount
#             port:
#               name: http
