---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  gitImplementation: go-git
  interval: 30m0s
  ref:
    branch: master
  timeout: 20s
  url: https://github.com/kubernetes-sigs/metrics-server
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  force: false
  interval: 1h0m0s
  patchesStrategicMerge:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: metrics-server
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
            - name: metrics-server
              args:
                - --cert-dir=/tmp
                - --secure-port=443
                - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
                - --kubelet-use-node-status-port
                - --metric-resolution=15s
                - --kubelet-insecure-tls
                - --kubelet-preferred-address-types=InternalIP
  path: ./manifests/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: metrics-server
  timeout: 2m0s
