#!/usr/bin/env bash
set -eu -o pipefail

if [[ "$(uname -s)" == "Darwin" ]]; then
  brew install kind
  brew install fluxcd/tap/flux
else
  curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.0/kind-linux-amd64
  chmod +x ./kind
  export PATH="${PATH}:$(pwd)"

  curl -s https://fluxcd.io/install.sh | sudo bash
fi

if ! kind get clusters | grep mrdefenestrator; then
  kind create cluster --name mrdefenestrator
fi

./flux-up
