#!/usr/bin/env bash
set -eu -o pipefail

if ! kind get clusters | grep threatx; then
  kind create cluster --name threatx
fi

# eksctl create cluster

# flux bootstrap github \
#   --branch=dev \
#   --owner threatxlabs \
#   --path=kube/kustomize \
#   --repository devops-hw-mg \
#   --token-auth

docker build -t devops images/devops
docker run -it devops -- hello
